# Site settings
title: Rafael Pazini
email: rflpazini@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://rflpazini.github.com" # the base hostname & protocol for your site

safe:        false
baseurl:     /
url: http://localhost:4000

name: Rafael Pazini
description: #Add one later
commentlinks: true
url: http://rflpazini.github.io
domain: github.io

# Build settings
markdown: kramdown
highlighter: pygments

paginate_path: 'blog/page:num'
future:      true
lsi:         false
pygments:    false
permalink:   /:title/
paginate: 5

github: [Repository metadata]
source:      .
destination: ./_site
plugins:     ./_plugins

# Social links 
twitter_username: RafaelPazini
github_username:  rflpazini
instagram_username: rafaelpazini
facebook_username: RafaPazini
plus_username: +RafaelPazini

