# Site settings
title: Rafael Pazini
email: rflpazini@gmail.com
name: Rafael Pazini
description: This is my project for my personal site/blog to talk about front-end and back-end development.
commentlinks: true
url: http://rflpazini.com
domain: rflpazini.com
google: UA-65133136-1

safe:        false
baseurl:     /
excerpt_separator: <!--more-->


# Build settings
markdown: kramdown
highlighter: pygments

paginate_path: 'blog/page:num'
future:      true
lsi:         false
pygments:    false
permalink:   /:title/
paginate: 5

github: [Repository metadata]
source:      .
destination: ./_site
plugins:     ./_plugins

# Social links
twitter_username: RafaelPazini
github_username:  rflpazini
instagram_username: rafaelpazini
facebook_username: RafaPazini
plus_username: +RafaelPazini
