# Site settings
title: Rafael Pazini
email: rflpazini@gmail.com
name: Rafael Pazini
description: This is my project for my personal site/blog to talk about front-end and back-end development.
commentlinks: true
url: https://rflpazini.com
domain: rflpazini.com
google: UA-65133136-1

safe:        false
baseurl:     /
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate_path: 'blog/page:num'
future:      true
lsi:         false
# permalink:   /:title/
paginate: 5

github: [Repository metadata]
source:      .
destination: ./_site
plugins_dir: ./_plugins

# Social links
twitter_username: RafaelPazini
github_username:  rflpazini
instagram_username: rafaelpazini
facebook_username: RafaPazini
plus_username: +RafaelPazini
