# Site settings
title: Rafael Pazini
email: rflpazini@gmail.com
description: This is my project for my personal site/blog to talk about front-end and back-end development.
commentlinks: true
url: http://rflpazini.com
enforce_ssl: rflpazini.com
domain: rflpazini.com
image_url: https://dl.dropboxusercontent.com/u/104095732/rflpazini.jpg
google: UA-65133136-1

safe:        false
baseurl:     /
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate, ]
paginate_path: 'blog/page:num'
future:      true
lsi:         false
permalink:   /:title/
paginate: 3

github: [Repository metadata]
source:      .
destination: ./_site
plugins_dir: ./_plugins
jekyll-crosspost_to_medium:
  enabled: true
  cache: .jekyll-crosspost_to_medium
  status: draft
  license: all-rights-reserved
  backdate: true

# Social links
twitter_username: RafaelPazini
github_username:  rflpazini
instagram_username: rafaelpazini
facebook_username: RafaPazini
plus_username: +RafaelPazini
linkedin_username: rafaelpazini
